# Assignment 1

**범위**

- 1.1 Python Basics
- 1.2 Tuple, List, Dictionary, Set
- 2.1 Conditions
- 2.2 Loops

# Q1. `range()`를 사용하여 0~9의 값을 가지는 리스트 `q1`을 선언하시오.

In [ ]:
q1 = list(range(10))

# Q2. Slicing을 사용하여 `q1`에서 짝수만 출력하시오.

In [ ]:
print(q1[::2])

[0, 2, 4, 6, 8]

# Q3. Slicing을 사용하여 `q1`에서 홀수만 출력하시오.

In [ ]:
print(q1[1::2])

[1, 3, 5, 7, 9]

# Q4. `q1`에서 index 2의 값을 200으로 변경하시오.

In [ ]:
q1[2] = 200
print(q1)

[0, 1, 200, 3, 4, 5, 6, 7, 8, 9]

# Q5. 아래 세 가지 방법으로 사용하여 `q1` 리스트 마지막에 100, 200, 300을 하나씩 추가하시오.

## Q5-1 `append` 사용 (100 추가)

In [ ]:
q1.append(100)
print(q1)

[0, 1, 200, 3, 4, 5, 6, 7, 8, 9, 100]

## Q5-2 `insert` 사용 (200 추가)

In [ ]:
q1.insert(len(q1), 200)
print(q1)

[0, 1, 200, 3, 4, 5, 6, 7, 8, 9, 100, 200]

## Q5-3 `+` 연산자 사용 (300 추가)

In [ ]:
q1 = q1 + [300]
print(q1)

[0, 1, 200, 3, 4, 5, 6, 7, 8, 9, 100, 200, 300]

# Q6. 'Python is a nice Programming Language'를 띄어쓰기 기준으로 분할하여 리스트 `q6`으로 저장하시오.

In [25]:
q6 = "Python is a nice Programming Language".split()
print(q6)

['Python', 'is', 'a', 'nice', 'Programming', 'Language']

# Q7. `q6`을 문자열 길이를 기준으로 오름차순 정렬하여 `q7`를 선언하시오.

In [ ]:
q7 = sorted(q6, key=len)
print(q7)

['a', 'is', 'nice', 'Python', 'Language', 'Programming']

# Q8. 비어있는 dictionary `dict_q8`을 선언하고, 본인의 이름과 학번을 각각 key와 value로 하여 `dict_q8`에 추가하시오.

In [ ]:
dict_q8 = {}
dict_q8["김예진"] = "2025170935"
print(dict_q8)

{'김예진': '2025170935'}

# Q9. 아래 두 리스트를 선언하고 두 질문에 대하여 답하시오.

```python
list1 = [1,2,3,4]
list2 = [1,2,3,4]
```

In [ ]:
list1 = [1, 2, 3, 4]
list2 = [1, 2, 3, 4]

## Q9-1 두 리스트의 값이 같음을 보이시오.

In [ ]:
print(list1 == list2)

True

## Q9-2 두 리스트의 주소값이 다름을 보이시오.

In [ ]:
print(list1 is list2)

False

# Q10. 변수 `year`에 연도를 선언하여 `year`가 윤년이면 True, 윤년이 아니면 `False`를 출력하는 코드를 작성하시오.

**윤년 조건**
- 4의 배수이면서 100의 배수는 아닌 경우
- 4와 100의 배수이나 400의 배수인 경우

In [26]:
year = 2028

if year % 4 == 0 and year % 100 !=0:
    print('True')

elif year % 4 == 0 and year % 100 == 0 and year % 400 ==0:
    print('True')

else:
    print('False')

True

# Q11. 두 개 list인 `names`과 `locations`가 있을 때 아래 질문에 맞게 코드를 작성 후 출력하시오.

```python
names = ['한상차림', '전주 외할머니댁', '보문수산']
locations = ['서울 동대문구 한빛로 28 1층', '서울 동대문구 무학로30길 22', '서울 성북구 보문로 102-6']
```

1. `names`와 `locations` 리스트를 사용하여 음식점 이름을 key로 하고, 위치를 value로 하는 dictionary를 생성하시오.
2. 반복문을 사용하여 음식점 이름과 위치를 출력하시오. 출력 형식은 '`이름`: `위치`' 입니다.

In [ ]:
names = ['한상차림', '전주 외할머니댁', '보문수산']
locations = ['서울 동대문구 한빛로 28 1층', '서울 동대문구 무학로30길 22', '서울 성북구 보문로 102-6']

restaurants = dict(zip(names, locations))

for name, location in restaurants.items():
    print(f"{name}: {location}")

한상차림: 서울 동대문구 한빛로 28 1층
전주 외할머니댁: 서울 동대문구 무학로30길 22
보문수산: 서울 성북구 보문로 102-6

# Q11. 아래 python 코드를 한 줄로 나타내시오.

```python
L = []
for k in range(10):
    if k % 2 == 1:
        L.append(k*k)
    else
        pass

print(L)
````

In [27]:
L = [k*k for k in range(10) if k % 2 == 1] ; print(L)

[1, 9, 25, 49, 81]

# Q12. 아래와 같이 두 벡터가 존재할 때 cosine similarity 수식을 참고하여 코드를 통해 유사도를 계산하시오. (수업 시 배운 내용만 참고할 것)

```python
X = [3,2,1,5,2,3,5]
Y = [9,3,1,5,2,4,3]
```

$$cos(\theta)=\frac{\sum_i^n{X_iY_i}}{\sqrt{\sum_i^n{X_i^2}}\sqrt{\sum_i^n{Y_i^2}}}$$

In [28]:
X = [3,2,1,5,2,3,5]
Y = [9,3,1,5,2,4,3]

sum_xy = 0
sum_x2 = 0
sum_y2 = 0

for i in range(len(X)):
    sum_xy += X[i] * Y[i]
    sum_x2 += X[i] ** 2
    sum_y2 += Y[i] ** 2

cosine_similarity = sum_xy / ((sum_x2**(1/2))*(sum_y2**(1/2)))

print(cosine_similarity)

0.851751968084951